export const branches = [
  { id: 1, branch_id: '010', name: 'LAO - VIET BANK, HEAD OFFICE' },
  { id: 2, branch_id: '011', name: 'SALAKHAM BANKING UNIT' },
  { id: 3, branch_id: '012', name: 'MORNING MARKET UNIT' },
  { id: 4, branch_id: '013', name: 'SYKHAY SERVICES UNIT' },
  { id: 5, branch_id: '014', name: 'DONGDOK SERVICES UNIT' },
  { id: 6, branch_id: '015', name: 'LAO VIET BANK, DONNOUN SERVICE UNIT' },
  { id: 7, branch_id: '016', name: 'LAO VIET BANK, ITECC Service Unit' },
  { id: 8, branch_id: '017', name: 'LAOVIET BANK, WATTAY UNIT' },
  { id: 9, branch_id: '018', name: 'Lao Viet Joint Venture Bank - Naxay' },
  { id: 10, branch_id: '030', name: 'LAO - VIET BANK CHAMPASAK BRANCH' },
  { id: 11, branch_id: '031	', name: 'LAO VIET BANK, TRANSACTION DEPT KM8' },
  { id: 12, branch_id: '032', name: 'LAOVIETBANK DUANGDY TRN UNIT' },
  { id: 13, branch_id: '050', name: 'LAO - VIET BANK SAVANAKHET BRANCH' },
  { id: 14, branch_id: '051', name: 'LAOVIETBANK SENO Service Unit' },
  { id: 15, branch_id: '052', name: 'LAOVIET BANK DENSAVANH TRN UNIT' },
  { id: 16, branch_id: '053', name: 'LAOVIET BANK KAYSONE TRN UNIT' },
  { id: 17, branch_id: '060', name: 'LAO - VIET BANK ATTAPEU BRANCH' },
  { id: 18, branch_id: '070', name: 'LAO-VIET BANK XIENGKHOANG BRANCH' },
  { id: 19, branch_id: '071', name: 'LAOVIET BANK PHONSAVANH UNIT' },
  { id: 20, branch_id: '080', name: 'LAO-VIET BANK LUANGPRABANG BRANCH' },
  { id: 21, branch_id: '081', name: 'LAOVIET BANK NO.1 Transaction Unit' },
  { id: 22, branch_id: '090', name: 'LAO-VIET BANK KHAMMOUAN BRANCH' },
  { id: 23, branch_id: '091', name: 'LAOVIETBANK NO.3 MARKET ZONE TRAN' },
  { id: 24, branch_id: '100', name: 'UODOMXAY BANKING UNIT' },
  { id: 25, branch_id: '110', name: 'LAO VIETBANK BOLIKHAMXAY UNIT' }
]
export const branchesLao = [
  { id: 1, branch_id: '010', name: 'ສຳນັກງານໃຫຍ່' },
  { id: 2, branch_id: '011', name: 'ໜ່ວຍບໍລິການ ສາລາຄຳ' },
  { id: 3, branch_id: '012', name: 'ໜ່ວຍບໍລິການ ຕະຫຼາດເຊົ້າ' },
  { id: 4, branch_id: '013', name: 'ໜ່ວຍບໍລິການ ສີໄຄ' },
  { id: 5, branch_id: '014', name: 'ໜ່ວຍບໍລິການ ດົງໂດກ' },
  { id: 6, branch_id: '015', name: 'ໜ່ວຍບໍລິການ ດອນໜຸນ' },
  { id: 7, branch_id: '016', name: 'ໜ່ວຍບໍລິການ ໄອເຕັກ' },
  { id: 8, branch_id: '017', name: 'ໜ່ວຍບໍລິການ ວັດໄຕ' },
  { id: 9, branch_id: '018', name: 'ໜ່ວຍບໍລິການ ນາໄຊ' },
  { id: 10, branch_id: '030', name: 'ສາຂາ ຈຳປາສັກ' },
  { id: 11, branch_id: '031	', name: 'ໜ່ວຍບໍລິການ TRANSACTION DEPT KM8' },
  { id: 12, branch_id: '032', name: 'ໜ່ວຍບໍລິການ ດວງດີ(ຈຳປາສັກ)' },
  { id: 13, branch_id: '050', name: 'ສາຂາ ສະຫວັນນະເຂດ' },
  { id: 14, branch_id: '051', name: 'ໜ່ວຍບໍລິການ ເຊໂນ(ສະຫວັນນະເຂດ)' },
  { id: 15, branch_id: '052', name: 'ໜ່ວຍບໍລິການ ແດນສະຫວັນ(ສະຫວັນນະເຂດ)' },
  { id: 16, branch_id: '053', name: 'ໜ່ວຍບໍລິການ ໄກສອນ(ສະຫວັນນະເຂດ)' },
  { id: 17, branch_id: '060', name: 'ສາຂາ ອັດຕະປື' },
  { id: 18, branch_id: '070', name: 'ສາຂາ ຊຽງຂວາງ' },
  { id: 19, branch_id: '071', name: 'ໜ່ວຍບໍລິການ ໂພນສະຫວັນ(ຊຽງຂວາງ)' },
  { id: 20, branch_id: '080', name: 'ສາຂາ ຫຼວງພະບາງ' },
  { id: 21, branch_id: '081', name: 'ໜ່ວຍບໍລິການ NO.1 Transaction Unit' },
  { id: 22, branch_id: '090', name: 'ສາຂາ ຄຳມ່ວນ' },
  { id: 23, branch_id: '091', name: 'ໜ່ວຍບໍລິການ NO.3 MARKET ZONE TRAN' },
  { id: 24, branch_id: '100', name: 'ສາຂາ ອຸດົມໄຊ' },
  { id: 25, branch_id: '110', name: 'ໜ່ວຍບໍລິການ ບໍລິຄຳໄຊ' }
]
